### ISSUE TITLE
Spigot/systemd enters restart loop when issuing the /restart command

### ISSUE THREAD

**Issue by ca1f** [nolte/ansible-minecraft#72] opened 2020-03-19 06:45 UTC
Hi!

I used your amazing ansible role to provision a minecraft 1.15.2 server with spigot. But it seems the server enters a restart loop when I issue the `/restart` command. Here is an extract from the journal:
<details>
<summary>log excerpt</summary>

```
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: ScrappyMan25 issued server command: /restart
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Startup script './start.sh' does not exist! Stopping server.
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Stopping server
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Saving players
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: RAZZARYAN lost connection: Server closed
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: RAZZARYAN left the game
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: eisenmagier lost connection: Server closed
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: eisenmagier left the game
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: ScrappyMan25 lost connection: Server closed
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: ScrappyMan25 left the game
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Aolsen96 lost connection: Server closed
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Aolsen96 left the game
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: RinSenya lost connection: Server closed
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: RinSenya left the game
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Saving worlds
Mar 18 22:28:28 nora java[13172]: [22:28:28] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
Mar 18 22:28:31 nora java[13172]: [22:28:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
Mar 18 22:28:31 nora java[13172]: [22:28:31] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
Mar 18 22:28:31 nora java[13172]: [22:28:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
Mar 18 22:28:31 nora java[13172]: [22:28:31] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
Mar 18 22:28:32 nora java[13172]: [22:28:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
Mar 18 22:28:32 nora java[13172]: [22:28:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
Mar 18 22:28:32 nora java[13172]: [22:28:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
Mar 18 22:28:32 nora java[13172]: [22:28:32] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
Mar 18 22:28:33 nora systemd[1]: spigot.service: Succeeded.
Mar 18 22:28:33 nora systemd[1]: Started Spigot Server.
Mar 18 22:28:33 nora java[13252]: Loading libraries, please wait...
Mar 18 22:28:38 nora java[13252]: [22:28:38] [Server thread/INFO]: Starting minecraft server version 1.15.2
Mar 18 22:28:38 nora java[13252]: [22:28:38] [Server thread/INFO]: Loading properties
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: Debug logging is disabled
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: Using 4 threads for Netty based IO
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: Server Ping Player Sample Count: 12
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: Default game type: SURVIVAL
Mar 18 22:28:39 nora java[13252]: [22:28:39] [Server thread/INFO]: Generating keypair
Mar 18 22:28:40 nora java[13252]: [22:28:40] [Server thread/INFO]: Starting Minecraft server on *:25565
Mar 18 22:28:40 nora java[13252]: [22:28:40] [Server thread/INFO]: Using epoll channel type
Mar 18 22:28:40 nora java[13252]: [22:28:40] [Server thread/INFO]: Preparing level "world"
Mar 18 22:28:40 nora java[13252]: [22:28:40] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit, anti enderman grief v1.0.0.zip, double shulker shells v1.0.3.zip, dragon drops elytra v1.0.2.zip, more mob heads v2.2.0.zip, multiplayer sleep v1.0.1.zip, player head drops v1.0.0.zip, redstone rotation wrench v1.0.1.zip, silence mobs v1.0.0.zip
Mar 18 22:28:47 nora java[13252]: [22:28:47] [Server thread/INFO]: Loaded 6 recipes
Mar 18 22:28:47 nora java[13252]: [22:28:47] [Server thread/WARN]: Datapack tried to redefine minecraft:empty loot table, ignoring
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Loaded 22 custom command functions
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: -------- World Settings For [world] --------
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Experience Merge Radius: 3.0
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Mob Spawn Range: 6
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Cactus Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Cane Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Melon Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Mushroom Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Sapling Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Beetroot Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Carrot Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Potato Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Wheat Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: NetherWart Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Vine Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Cocoa Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Bamboo Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Kelp Growth Modifier: 100%
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Max TNT Explosions: 100
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: View Distance: 10
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Item Despawn Rate: 6000
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Item Merge Radius: 2.5
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
Mar 18 22:28:48 nora java[13252]: [22:28:48] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: -------- World Settings For [world_nether] --------
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Experience Merge Radius: 3.0
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Mob Spawn Range: 6
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cane Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Melon Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Potato Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Vine Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Max TNT Explosions: 100
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: View Distance: 10
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Item Despawn Rate: 6000
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Item Merge Radius: 2.5
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Experience Merge Radius: 3.0
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Mob Spawn Range: 6
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cactus Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cane Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Melon Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Mushroom Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Sapling Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Beetroot Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Carrot Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Potato Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Wheat Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: NetherWart Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Vine Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Cocoa Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Bamboo Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Kelp Growth Modifier: 100%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Max TNT Explosions: 100
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: View Distance: 10
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Item Despawn Rate: 6000
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Item Merge Radius: 2.5
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Preparing start region for dimension 'world'/minecraft:overworld
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:49 nora java[13252]: [22:28:49] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:50 nora java[13252]: [22:28:50] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:50 nora java[13252]: [22:28:50] [Server thread/INFO]: Time elapsed: 1456 ms
Mar 18 22:28:50 nora java[13252]: [22:28:50] [Server thread/INFO]: Preparing start region for dimension 'world_nether'/minecraft:the_nether
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Time elapsed: 724 ms
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Preparing start region for dimension 'world_the_end'/minecraft:the_end
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Preparing spawn area: 0%
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Time elapsed: 347 ms
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Done (11.240s)! For help, type "help"
Mar 18 22:28:51 nora java[13252]: [22:28:51] [Server thread/INFO]: Saving the game (this may take a moment!)
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saved the game
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Stopping the server
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Stopping server
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saving players
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saving worlds
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
Mar 18 22:28:52 nora java[13252]: [22:28:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
Mar 18 22:28:53 nora systemd[1]: spigot.service: Succeeded.
Mar 18 22:28:53 nora systemd[1]: Started Spigot Server.
Mar 18 22:28:53 nora java[13314]: Loading libraries, please wait...
Mar 18 22:28:58 nora java[13314]: [22:28:58] [Server thread/INFO]: Starting minecraft server version 1.15.2
Mar 18 22:28:58 nora java[13314]: [22:28:58] [Server thread/INFO]: Loading properties
Mar 18 22:28:58 nora java[13314]: [22:28:58] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

</details>

This goes on until I stop both the `spigot.service` and the `spigot.socket` unit. Do you have an idea what I'm doing/what's going wrong here?

**Comment by nolte** [comment] 2020-03-19 16:38
Thanks for the feedback, i will take a look.

I think the Problem is the [ListenFIFO=](https://github.com/nolte/ansible-minecraft/blob/develop/templates/minecraft.socket.j2#L5) in combination with  [ExecStop](https://github.com/nolte/ansible-minecraft/blob/develop/templates/minecraft.service.j2#L16)

**Comment by sas101** [comment] 2022-05-19 20:46
I ran into this as well, but with the vanilla minecraft server on a fresh Ubuntu 22.04
Looks like I fixed it for me:
I added RestartPreventExitStatus=143 to the minecraft.service definition: 
https://www.freedesktop.org/software/systemd/man/systemd.service.html#RestartPreventExitStatus=
Can send you a PR, if you want.

**Comment by the-technat** [comment] 2022-06-15 09:33
I can confirm that on Debian 11 using Openjdk 17 this is an issue too and `RestartPreventExitStatus=143` fixes it. I'm adding a PR for that...

**Comment by sas101** [comment] 2022-07-07 07:42
Great! Thanks @the-technat 
@nolte pls merge and release a fix version :)

**Comment by nolte** [comment] 2022-07-07 19:24
Thanks for your helpe, the fix are released with
 [v6.1.1](https://github.com/nolte/ansible-minecraft/releases/tag/v6.1.1).

**Closed as completed by nolte** 2022-07-07 19:24 UTC
Labels: bug, help wanted

**Comment by sas101** [comment] 2022-07-07 21:17
I just used the updated version 6.1.1 to update my minecraft server and now it works out-of-the-box.
Thanks @nolte !
